[
    {
        "project": "CryptoBeastofWar_1",
        "policies": [
            "6841291a0e213f13105c466d6a4f4e81147590eae130c73703ca3c8c"
        ]
    },
    {
        "project": "Spring",
        "policies": [
            "456f0cd676347550d217f1d1dbe0b616e675c5912e42f1e723bcf4a1"
        ]
    },
        {
        "project": "Dark forest",
        "policies": [
            "016bec7889b6bcb4195fd42845a0c472a211d63f7a84155b73ca48d5"
        ]
    },
         {
        "project": "Frozen baby",
        "policies": [
            "ebd580937d8bf751f65da0713787b42e7e569c86b24371c6caf40ab3"
        ]
    },   
        {
        "project": "MusicmyLife",
        "policies": [
            "f219e9ac3d768383dd96a2e5d800367c959da03091c7c8677f2a602e"
        ]
    },    
            {
        "project": "AntiquityStore",
        "policies": [
            "1a9fd00501bcb126fdf37985cca1e39d6bef69d71e613629976cb04b"
        ]
    },
       {
        "project": "RainyDayz",
        "policies": [
            "0aa71ddc0ceccab405b1a732775369921105f63e6ac38e5526a8b9a4"
        ]
    },
       {
        "project": "SouvenirsdeFrance",
        "policies": [
            "988d6115a06bd72016b303e6a3435e60997564d970650414288b3707"
        ]
    },
       {
        "project": "A sleeping Dandelion",
        "policies": [
            "95b34b1a3f85da2030df45859ab43dc4b62da35bfd8ad10bc3a9d30d"
        ]
    },
]
